//! Generating SDK wire types from a protocol's committed artifacts.
//!
//! What is generated is deliberately the *thin* half: constants, payload types,
//! and the typed call surface. The framing, the peer loop, and dispatch are
//! hand-written once per language and live in `sdks/`, because those are the
//! parts that are hard, identical across protocols, and worth fixing in one
//! place. Re-emitting a JSON-RPC loop per protocol per language is exactly the
//! duplication this kit exists to end.
//!
//! Type generation covers the shapes a protocol payload actually uses: objects
//! with named properties, arrays, primitives, references, and unions with null.
//! Anything outside that becomes the language's permissive type rather than a
//! generation failure, so an exotic payload costs precision, not a broken SDK.

use std::collections::BTreeMap;

use anyhow::Result;
use lanok_schema::ProtocolIndex;
use serde_json::Value;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    Python,
    TypeScript,
}

impl std::str::FromStr for Language {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self> {
        match s {
            "python" | "py" => Ok(Language::Python),
            "typescript" | "ts" => Ok(Language::TypeScript),
            other => Err(anyhow::anyhow!(
                "unknown language `{other}`; expected `python` or `typescript`"
            )),
        }
    }
}

pub fn render(index: &ProtocolIndex, language: Language) -> String {
    match language {
        Language::Python => python(index),
        Language::TypeScript => typescript(index),
    }
}

/// The named types from `$defs`, in a stable order.
fn definitions(index: &ProtocolIndex) -> BTreeMap<String, Value> {
    index
        .definitions()
        .as_object()
        .map(|defs| {
            defs.iter()
                .map(|(name, schema)| (name.clone(), schema.clone()))
                .collect()
        })
        .unwrap_or_default()
}

fn banner(index: &ProtocolIndex, comment: &str) -> String {
    format!(
        "{comment} Generated by `lanok gen` from the {} protocol, version {}.\n\
         {comment} Do not edit: regenerate instead, or the drift guard will fail.\n",
        index.name, index.version
    )
}

// ---------------------------------------------------------------------------
// Python

fn python(index: &ProtocolIndex) -> String {
    let mut out = String::new();
    out.push_str(&banner(index, "#"));
    out.push_str(
        "\nfrom __future__ import annotations\n\n\
         from typing import Any, Literal, NotRequired, TypedDict\n\n",
    );

    out.push_str(&format!("PROTOCOL = {:?}\n", index.name));
    out.push_str(&format!("VERSION = {:?}\n", index.version));
    out.push_str(&format!("MIN_VERSION = {:?}\n\n", index.min_version));

    if !index.capabilities.is_empty() {
        out.push_str("# Capability tokens this protocol defines.\n");
        for token in &index.capabilities {
            out.push_str(&format!(
                "{} = {token:?}\n",
                token.to_uppercase().replace(['-', '/'], "_")
            ));
        }
        out.push('\n');
    }

    out.push_str("# Wire names, so a call site never spells a method as a string.\n");
    out.push_str("class method:\n");
    for entry in &index.methods {
        out.push_str(&format!(
            "    {} = {:?}\n",
            entry.ident().to_uppercase(),
            entry.name
        ));
    }
    out.push('\n');

    for (name, schema) in definitions(index) {
        out.push_str(&python_type(&name, &schema));
    }

    out.push_str("# Every method, with the direction it flows and what it needs.\n");
    out.push_str("METHODS: dict[str, dict[str, Any]] = {\n");
    for entry in &index.methods {
        out.push_str(&format!(
            "    {:?}: {{\"direction\": {:?}, \"kind\": {:?}, \"requires\": {}}},\n",
            entry.name,
            entry.direction,
            entry.kind,
            entry
                .requires
                .as_ref()
                .map(|r| format!("{r:?}"))
                .unwrap_or_else(|| "None".into())
        ));
    }
    out.push_str("}\n");
    out
}

fn python_type(name: &str, schema: &Value) -> String {
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        // Not an object shape: alias it rather than inventing a class.
        return format!("{name} = {}\n\n", python_scalar(schema));
    };

    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    let mut out = format!("class {name}(TypedDict):\n");
    if let Some(doc) = schema.get("description").and_then(Value::as_str) {
        out.push_str(&format!("    \"\"\"{doc}\"\"\"\n\n"));
    }
    if properties.is_empty() {
        out.push_str("    pass\n");
    }
    for (field, shape) in properties {
        let rendered = python_scalar(shape);
        let annotated = if required.contains(&field.as_str()) {
            rendered
        } else {
            format!("NotRequired[{rendered}]")
        };
        out.push_str(&format!("    {field}: {annotated}\n"));
    }
    out.push('\n');
    out
}

fn python_scalar(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference.rsplit('/').next().unwrap_or("Any").to_string();
    }
    if let Some(options) = schema.get("anyOf").or_else(|| schema.get("oneOf")) {
        return union(options, python_scalar, " | ", "Any");
    }
    match type_name(schema) {
        Some("string") => match schema.get("enum").and_then(Value::as_array) {
            Some(values) => format!(
                "Literal[{}]",
                values
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|v| format!("{v:?}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            None => "str".into(),
        },
        Some("integer") => "int".into(),
        Some("number") => "float".into(),
        Some("boolean") => "bool".into(),
        Some("null") => "None".into(),
        Some("array") => format!(
            "list[{}]",
            schema
                .get("items")
                .map(python_scalar)
                .unwrap_or_else(|| "Any".into())
        ),
        Some("object") => "dict[str, Any]".into(),
        _ => "Any".into(),
    }
}

// ---------------------------------------------------------------------------
// TypeScript

fn typescript(index: &ProtocolIndex) -> String {
    let mut out = String::new();
    out.push_str(&banner(index, "//"));
    out.push('\n');

    out.push_str(&format!(
        "export const PROTOCOL = {:?} as const;\n",
        index.name
    ));
    out.push_str(&format!(
        "export const VERSION = {:?} as const;\n",
        index.version
    ));
    out.push_str(&format!(
        "export const MIN_VERSION = {:?} as const;\n\n",
        index.min_version
    ));

    if !index.capabilities.is_empty() {
        out.push_str("/** Capability tokens this protocol defines. */\n");
        out.push_str("export const capability = {\n");
        for token in &index.capabilities {
            out.push_str(&format!("  {}: {token:?},\n", camel(token)));
        }
        out.push_str("} as const;\n\n");
    }

    out.push_str("/** Wire names, so a call site never spells a method as a string. */\n");
    out.push_str("export const method = {\n");
    for entry in &index.methods {
        out.push_str(&format!("  {}: {:?},\n", camel(&entry.ident()), entry.name));
    }
    out.push_str("} as const;\n\n");

    for (name, schema) in definitions(index) {
        out.push_str(&typescript_type(&name, &schema));
    }

    out.push_str("/** Every method, with the direction it flows and what it needs. */\n");
    out.push_str(
        "export const METHODS: Record<string, { direction: string; kind: string; requires: string | null }> = {\n",
    );
    for entry in &index.methods {
        out.push_str(&format!(
            "  {:?}: {{ direction: {:?}, kind: {:?}, requires: {} }},\n",
            entry.name,
            entry.direction,
            entry.kind,
            entry
                .requires
                .as_ref()
                .map(|r| format!("{r:?}"))
                .unwrap_or_else(|| "null".into())
        ));
    }
    out.push_str("};\n");
    out
}

fn typescript_type(name: &str, schema: &Value) -> String {
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return format!("export type {name} = {};\n\n", typescript_scalar(schema));
    };

    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    let mut out = String::new();
    if let Some(doc) = schema.get("description").and_then(Value::as_str) {
        out.push_str(&format!("/** {doc} */\n"));
    }
    out.push_str(&format!("export interface {name} {{\n"));
    for (field, shape) in properties {
        let optional = if required.contains(&field.as_str()) {
            ""
        } else {
            "?"
        };
        if let Some(doc) = shape.get("description").and_then(Value::as_str) {
            out.push_str(&format!("  /** {doc} */\n"));
        }
        out.push_str(&format!(
            "  {field}{optional}: {};\n",
            typescript_scalar(shape)
        ));
    }
    out.push_str("}\n\n");
    out
}

fn typescript_scalar(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .unwrap_or("unknown")
            .to_string();
    }
    if let Some(options) = schema.get("anyOf").or_else(|| schema.get("oneOf")) {
        return union(options, typescript_scalar, " | ", "unknown");
    }
    match type_name(schema) {
        Some("string") => match schema.get("enum").and_then(Value::as_array) {
            Some(values) => values
                .iter()
                .filter_map(Value::as_str)
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(" | "),
            None => "string".into(),
        },
        Some("integer") | Some("number") => "number".into(),
        Some("boolean") => "boolean".into(),
        Some("null") => "null".into(),
        Some("array") => format!(
            "Array<{}>",
            schema
                .get("items")
                .map(typescript_scalar)
                .unwrap_or_else(|| "unknown".into())
        ),
        Some("object") => "Record<string, unknown>".into(),
        _ => "unknown".into(),
    }
}

// ---------------------------------------------------------------------------
// Shared

/// `type` may be a string or an array (schemars emits `["string", "null"]` for
/// an Option). Take the first non-null entry: the nullability is carried by the
/// field being optional.
fn type_name(schema: &Value) -> Option<&str> {
    match schema.get("type")? {
        Value::String(name) => Some(name),
        Value::Array(names) => names
            .iter()
            .filter_map(Value::as_str)
            .find(|n| *n != "null")
            .or(Some("null")),
        _ => None,
    }
}

fn union(options: &Value, render: fn(&Value) -> String, join: &str, fallback: &str) -> String {
    let rendered: Vec<String> = options
        .as_array()
        .map(|options| options.iter().map(render).collect())
        .unwrap_or_default();
    if rendered.is_empty() {
        return fallback.to_string();
    }
    rendered.join(join)
}

/// `tool_call` becomes `toolCall`, which is what a TypeScript reader expects.
fn camel(input: &str) -> String {
    let mut out = String::new();
    let mut capitalize = false;
    for c in input.chars() {
        if c == '_' || c == '-' || c == '/' {
            capitalize = true;
        } else if capitalize {
            out.extend(c.to_uppercase());
            capitalize = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn optional_fields_are_optional_in_both_languages() {
        let schema = json!({
            "properties": { "text": { "type": "string" }, "shout": { "type": "boolean" } },
            "required": ["text"]
        });
        let python = python_type("EchoParams", &schema);
        assert!(python.contains("text: str"));
        assert!(python.contains("shout: NotRequired[bool]"));

        let typescript = typescript_type("EchoParams", &schema);
        assert!(typescript.contains("text: string;"));
        assert!(typescript.contains("shout?: boolean;"));
    }

    #[test]
    fn an_option_renders_as_the_inner_type() {
        // schemars emits ["string", "null"] for Option<String>; the nullability
        // is already carried by the field being absent from `required`.
        let schema = json!({ "type": ["string", "null"] });
        assert_eq!(python_scalar(&schema), "str");
        assert_eq!(typescript_scalar(&schema), "string");
    }

    #[test]
    fn references_become_named_types() {
        let schema = json!({ "$ref": "#/$defs/AskResult" });
        assert_eq!(python_scalar(&schema), "AskResult");
        assert_eq!(typescript_scalar(&schema), "AskResult");
    }

    #[test]
    fn arrays_and_enums_keep_their_shape() {
        let array = json!({ "type": "array", "items": { "type": "integer" } });
        assert_eq!(python_scalar(&array), "list[int]");
        assert_eq!(typescript_scalar(&array), "Array<number>");

        let choice = json!({ "type": "string", "enum": ["yes", "no"] });
        assert_eq!(python_scalar(&choice), r#"Literal["yes", "no"]"#);
        assert_eq!(typescript_scalar(&choice), r#""yes" | "no""#);
    }

    #[test]
    fn an_unknown_shape_degrades_instead_of_failing() {
        // Precision is lost, the SDK still builds. A protocol with an exotic
        // payload should not be ungeneratable.
        let exotic = json!({ "not": { "type": "string" } });
        assert_eq!(python_scalar(&exotic), "Any");
        assert_eq!(typescript_scalar(&exotic), "unknown");
    }

    #[test]
    fn wire_names_become_idiomatic_identifiers() {
        assert_eq!(camel("tool_call"), "toolCall");
        assert_eq!(camel("ui_ask"), "uiAsk");
        assert_eq!(camel("echo"), "echo");
    }
}
