# Generated by `lanok gen` from the echo protocol, version 1.0.
# Do not edit: regenerate instead, or the drift guard will fail.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

PROTOCOL = "echo"
VERSION = "1.0"
MIN_VERSION = "1.0"

# Capability tokens this protocol defines.
UI_ASK = "ui_ask"

# Wire names, so a call site never spells a method as a string.
class method:
    ECHO = "echo"
    PING = "ping"
    ECHO_PROGRESS = "echo/progress"
    UI_ASK = "ui/ask"

class AskParams(TypedDict):
    question: str

class AskResult(TypedDict):
    answer: str

class EchoParams(TypedDict):
    shout: NotRequired[bool]
    text: str

class EchoResult(TypedDict):
    text: str

class ProgressParams(TypedDict):
    of: int
    step: int

# Every method, with the direction it flows and what it needs.
METHODS: dict[str, dict[str, Any]] = {
    "echo": {"direction": "initiator", "kind": "request", "requires": None},
    "ping": {"direction": "initiator", "kind": "request", "requires": None},
    "echo/progress": {"direction": "responder", "kind": "notification", "requires": None},
    "ui/ask": {"direction": "responder", "kind": "request", "requires": "ui_ask"},
}
