// Generated by `lanok gen` from the echo protocol, version 1.0.
// Do not edit: regenerate instead, or the drift guard will fail.

export const PROTOCOL = "echo" as const;
export const VERSION = "1.0" as const;
export const MIN_VERSION = "1.0" as const;

/** Capability tokens this protocol defines. */
export const capability = {
  uiAsk: "ui_ask",
} as const;

/** Wire names, so a call site never spells a method as a string. */
export const method = {
  echo: "echo",
  ping: "ping",
  echoProgress: "echo/progress",
  uiAsk: "ui/ask",
} as const;

export interface AskParams {
  question: string;
}

export interface AskResult {
  answer: string;
}

export interface EchoParams {
  /** The text to transform. */
  text: string;
  /** Uppercase it. Defaults to false, like every optional lanok field, so a
peer that predates this field still parses. */
  shout?: boolean;
}

export interface EchoResult {
  text: string;
}

export interface ProgressParams {
  step: number;
  of: number;
}

/** Every method, with the direction it flows and what it needs. */
export const METHODS: Record<string, { direction: string; kind: string; requires: string | null }> = {
  "echo": { direction: "initiator", kind: "request", requires: null },
  "ping": { direction: "initiator", kind: "request", requires: null },
  "echo/progress": { direction: "responder", kind: "notification", requires: null },
  "ui/ask": { direction: "responder", kind: "request", requires: "ui_ask" },
};
