//! What a peer does with an inbound message.
//!
//! A handler is installed on both sides. That is the whole point: a "client"
//! that answers `ui/ask` and a "server" that answers `tool/call` run the same
//! machinery, differing only in which methods they registered.

use std::future::Future;
use std::pin::Pin;

use lanok_core::{RpcError, Value};

/// A boxed future returning one request's outcome.
pub type HandlerFuture = Pin<Box<dyn Future<Output = Result<Value, RpcError>> + Send>>;

/// Answers inbound requests and notifications.
///
/// Implemented by hand for a dynamic dispatcher, or generated by
/// `lanok::protocol!` for a declared protocol. The default answers reject
/// everything, so a peer that registers nothing is a well-behaved client rather
/// than a silent hole: an unexpected request gets `method not found` instead of
/// hanging the caller until its timeout.
pub trait Handler: Send + Sync + 'static {
    /// Answer a request. The returned future must be `Send`: requests are
    /// handled concurrently, each on its own task.
    fn request(&self, method: String, params: Value) -> HandlerFuture {
        Box::pin(async move {
            let _ = params;
            Err(RpcError::method_not_found(&method))
        })
    }

    /// Observe a notification. Nothing is sent back, by definition, so an error
    /// here has nowhere to go and the implementation swallows or logs it.
    fn notification(&self, method: String, params: Value) {
        let _ = (method, params);
    }
}

/// A peer that answers nothing. The default for a pure caller.
#[derive(Debug, Default, Clone, Copy)]
pub struct NoHandler;

impl Handler for NoHandler {}

/// A method table, for peers that dispatch by hand rather than from a
/// `protocol!` declaration.
///
/// ```
/// # use lanok_peer::{Handler, Router};
/// # use serde_json::json;
/// let router = Router::new().on_request("echo", |params| async move { Ok(params) });
/// # let _ = router;
/// ```
pub struct Router {
    requests: std::collections::HashMap<String, Box<dyn Fn(Value) -> HandlerFuture + Send + Sync>>,
    notifications: std::collections::HashMap<String, Box<dyn Fn(Value) + Send + Sync>>,
}

impl std::fmt::Debug for Router {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Router")
            .field("requests", &self.requests.keys().collect::<Vec<_>>())
            .field(
                "notifications",
                &self.notifications.keys().collect::<Vec<_>>(),
            )
            .finish()
    }
}

impl Default for Router {
    fn default() -> Self {
        Self::new()
    }
}

impl Router {
    pub fn new() -> Self {
        Router {
            requests: std::collections::HashMap::new(),
            notifications: std::collections::HashMap::new(),
        }
    }

    /// Answer `method` with an async function of its params.
    pub fn on_request<F, Fut>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Result<Value, RpcError>> + Send + 'static,
    {
        self.requests.insert(
            method.into(),
            Box::new(move |params| Box::pin(handler(params))),
        );
        self
    }

    /// Observe `method`.
    pub fn on_notification<F>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Value) + Send + Sync + 'static,
    {
        self.notifications.insert(method.into(), Box::new(handler));
        self
    }
}

impl Handler for Router {
    fn request(&self, method: String, params: Value) -> HandlerFuture {
        match self.requests.get(&method) {
            Some(handler) => handler(params),
            None => Box::pin(async move { Err(RpcError::method_not_found(&method)) }),
        }
    }

    fn notification(&self, method: String, params: Value) {
        if let Some(handler) = self.notifications.get(&method) {
            handler(params);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lanok_core::codes;

    #[tokio::test]
    async fn the_default_rejects_rather_than_hangs() {
        let error = NoHandler
            .request("anything".into(), Value::Null)
            .await
            .unwrap_err();
        assert_eq!(error.code, codes::METHOD_NOT_FOUND);
    }
}
