//! What a peer does with an inbound message.
//!
//! A handler is installed on both sides. That is the whole point: a "client"
//! that answers `ui/ask` and a "server" that answers `tool/call` run the same
//! machinery, differing only in which methods they registered.

use std::future::Future;
use std::pin::Pin;

use lanok_core::{RpcError, Value};

use crate::context::Context;

/// A boxed future returning one request's outcome.
pub type HandlerFuture = Pin<Box<dyn Future<Output = Result<Value, RpcError>> + Send>>;

/// Answers inbound requests and notifications.
///
/// Implemented by hand for a dynamic dispatcher, or generated by
/// `lanok::protocol!` for a declared protocol. The default answers reject
/// everything, so a peer that registers nothing is a well-behaved client rather
/// than a silent hole: an unexpected request gets `method not found` instead of
/// hanging the caller until its timeout.
pub trait Handler: Send + Sync + 'static {
    /// Answer a request. The returned future must be `Send`: requests are
    /// handled concurrently, each on its own task.
    ///
    /// `cx` is the request itself: its id, and the means to emit progress
    /// against that id before the response lands. It is passed by value
    /// because the returned future is `'static` and cannot borrow.
    fn request(&self, cx: Context, method: String, params: Value) -> HandlerFuture {
        Box::pin(async move {
            let _ = (cx, params);
            Err(RpcError::method_not_found(&method))
        })
    }

    /// Observe a notification. Nothing is sent back, by definition, so an error
    /// here has nowhere to go and the implementation swallows or logs it.
    ///
    /// `cx` carries no id here, for the same reason: a notification is not a
    /// request and has nothing to correlate to.
    fn notification(&self, cx: Context, method: String, params: Value) {
        let _ = (cx, method, params);
    }
}

/// A peer that answers nothing. The default for a pure caller.
#[derive(Debug, Default, Clone, Copy)]
pub struct NoHandler;

impl Handler for NoHandler {}

type RequestFn = Box<dyn Fn(Context, Value) -> HandlerFuture + Send + Sync>;
type NotificationFn = Box<dyn Fn(Context, Value) + Send + Sync>;

/// A method table, for peers that dispatch by hand rather than from a
/// `protocol!` declaration.
///
/// ```
/// # use lanok_peer::{Handler, Router};
/// # use serde_json::json;
/// let router = Router::new().on_request("echo", |params| async move { Ok(params) });
/// # let _ = router;
/// ```
pub struct Router {
    requests: std::collections::HashMap<String, RequestFn>,
    notifications: std::collections::HashMap<String, NotificationFn>,
}

impl std::fmt::Debug for Router {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Router")
            .field("requests", &self.requests.keys().collect::<Vec<_>>())
            .field(
                "notifications",
                &self.notifications.keys().collect::<Vec<_>>(),
            )
            .finish()
    }
}

impl Default for Router {
    fn default() -> Self {
        Self::new()
    }
}

impl Router {
    pub fn new() -> Self {
        Router {
            requests: std::collections::HashMap::new(),
            notifications: std::collections::HashMap::new(),
        }
    }

    /// Answer `method` with an async function of its params.
    pub fn on_request<F, Fut>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Result<Value, RpcError>> + Send + 'static,
    {
        self.requests.insert(
            method.into(),
            Box::new(move |_cx, params| Box::pin(handler(params))),
        );
        self
    }

    /// Answer `method` with an async function that also gets the request:
    /// its id, and a way to emit progress against it.
    pub fn on_request_with<F, Fut>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Context, Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Result<Value, RpcError>> + Send + 'static,
    {
        self.requests.insert(
            method.into(),
            Box::new(move |cx, params| Box::pin(handler(cx, params))),
        );
        self
    }

    /// Observe `method`.
    pub fn on_notification<F>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Value) + Send + Sync + 'static,
    {
        self.notifications
            .insert(method.into(), Box::new(move |_cx, params| handler(params)));
        self
    }

    /// Observe `method`, with the context too.
    pub fn on_notification_with<F>(mut self, method: impl Into<String>, handler: F) -> Self
    where
        F: Fn(Context, Value) + Send + Sync + 'static,
    {
        self.notifications.insert(method.into(), Box::new(handler));
        self
    }
}

impl Handler for Router {
    fn request(&self, cx: Context, method: String, params: Value) -> HandlerFuture {
        match self.requests.get(&method) {
            Some(handler) => handler(cx, params),
            None => Box::pin(async move { Err(RpcError::method_not_found(&method)) }),
        }
    }

    fn notification(&self, cx: Context, method: String, params: Value) {
        if let Some(handler) = self.notifications.get(&method) {
            handler(cx, params);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lanok_core::codes;

    #[tokio::test]
    async fn the_default_rejects_rather_than_hangs() {
        let error = NoHandler
            .request(Context::detached(), "anything".into(), Value::Null)
            .await
            .unwrap_err();
        assert_eq!(error.code, codes::METHOD_NOT_FOUND);
    }
}
